"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, Clock3, Copy, Plus, Users, Video } from "lucide-react";
import WorkspacePage from "../../components/WorkspacePage";
import Modal from "../../components/Modal";
import { api, AuthUser, Meeting } from "../../lib/api";

export default function MeetingsPage(){return <WorkspacePage active="meetings" title="Meetings" subtitle="View, start, and manage all your meetings.">{user=><MeetingsContent user={user}/>}</WorkspacePage>}
function MeetingsContent({user}:{user:AuthUser}){const router=useRouter();const [data,setData]=useState<{upcoming:Meeting[];recent:Meeting[]}>({upcoming:[],recent:[]});const [schedule,setSchedule]=useState(false);const [form,setForm]=useState({title:"",description:"",scheduled_at:"",duration_minutes:30});const [error,setError]=useState("");const load=()=>api.meetings().then(setData).catch(e=>setError(e.message));useEffect(()=>{load()},[]);async function submit(e:React.FormEvent){e.preventDefault();try{await api.schedule(form);setSchedule(false);load()}catch(e){setError((e as Error).message)}}return <>{error&&<div className="error">{error}</div>}<div className="page-actions"><button className="primary-action" onClick={()=>setSchedule(true)}><Plus/> Schedule meeting</button></div><div className="data-section"><h2>Upcoming <span>{data.upcoming.length}</span></h2>{data.upcoming.length?<div className="data-table">{data.upcoming.map(m=><div className="data-row" key={m.meeting_id}><div className="data-icon"><CalendarDays/></div><div className="data-main"><b>{m.title}</b><span>{new Date(m.scheduled_at).toLocaleString()} · {m.duration_minutes} min</span></div><button className="copy-btn" onClick={()=>navigator.clipboard.writeText(`${location.origin}/meeting/${m.meeting_id}`)}><Copy/> Invite</button><button className="join-btn" onClick={()=>router.push(`/meeting/${m.meeting_id}?name=${encodeURIComponent(user.name)}&host=1`)}><Video/> Start</button></div>)}</div>:<div className="empty"><CalendarDays/><h3>No upcoming meetings</h3><p>Schedule a meeting to get started.</p></div>}</div><div className="data-section"><h2>Past meetings <span>{data.recent.length}</span></h2>{data.recent.map(m=><div className="data-row" key={m.meeting_id}><div className="data-icon muted-icon"><Clock3/></div><div className="data-main"><b>{m.title}</b><span>{new Date(m.scheduled_at).toLocaleDateString()} · Hosted by {m.host_name}</span></div><span className="status-pill">Ended</span></div>)}</div>{schedule&&<Modal title="Schedule a meeting" onClose={()=>setSchedule(false)}><form className="form" onSubmit={submit}><label>Meeting title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-row"><label>Date & time<input required type="datetime-local" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></label><label>Duration<select value={form.duration_minutes} onChange={e=>setForm({...form,duration_minutes:Number(e.target.value)})}><option value="30">30 minutes</option><option value="60">1 hour</option><option value="90">90 minutes</option></select></label></div><button className="primary">Schedule</button></form></Modal>}</>}
