"use client";
import { useState } from "react";
import { Mail, Plus, Search, UserPlus, Video } from "lucide-react";
import WorkspacePage from "../../components/WorkspacePage";
import Modal from "../../components/Modal";

type Contact={name:string;email:string;status:string};
const initial:Contact[]=[{name:"Maya Chen",email:"maya@company.com",status:"Available"},{name:"Daniel Kim",email:"daniel@company.com",status:"In a meeting"},{name:"Priya Sharma",email:"priya@company.com",status:"Available"},{name:"Sam Wilson",email:"sam@company.com",status:"Away"}];
export default function ContactsPage(){return <WorkspacePage active="contacts" title="Contacts" subtitle="Find people and start a conversation.">{()=> <ContactsContent/>}</WorkspacePage>}
function ContactsContent(){const [contacts,setContacts]=useState(initial);const [query,setQuery]=useState("");const [open,setOpen]=useState(false);const [form,setForm]=useState({name:"",email:""});const filtered=contacts.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(query.toLowerCase()));function add(e:React.FormEvent){e.preventDefault();setContacts(c=>[...c,{...form,status:"Available"}]);setForm({name:"",email:""});setOpen(false)}return <><div className="page-toolbar"><div className="inner-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search contacts"/></div><button className="primary-action" onClick={()=>setOpen(true)}><UserPlus/> Add contact</button></div><div className="contact-grid">{filtered.map(c=><article className="contact-card" key={c.email}><div className="contact-avatar">{c.name.split(" ").map(x=>x[0]).join("")}</div><div><h3>{c.name}</h3><p><span className={`presence ${c.status==="Available"?"online":""}`}/>{c.status}</p></div><div className="contact-actions"><button title="Email" onClick={()=>location.href=`mailto:${c.email}`}><Mail/></button><button title="Start meeting" onClick={()=>alert(`Meeting invite prepared for ${c.name}`)}><Video/></button></div></article>)}</div>{!filtered.length&&<div className="empty"><Search/><h3>No contacts found</h3><p>Try another name or email.</p></div>}{open&&<Modal title="Add a contact" onClose={()=>setOpen(false)}><form className="form" onSubmit={add}><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><button className="primary"><Plus/> Add contact</button></form></Modal>}</>}
